name: Git Fetch
description: perform a git fetch on the checkout directory
author: terence@brex.com
requirements: ['git']
configuration:
  properties:
    depth:
      type: number
  additionalProperties: false
